### ISSUE TITLE
Mobile version shows gray bg after swiped to the left

### ISSUE THREAD

**Issue by aviadmini** [harnishdesign/iDocs#2]
1. Open template at [http://demo.harnishdesign.net/html/idocs/index-3.html](http://demo.harnishdesign.net/html/idocs/index-3.html) on mobile (I used Chrome)
2.  Swipe left anywhere on the body
3. Get result similar to this:
![Screenshot_20210715-194457_Chrome](https://user-images.githubusercontent.com/5710176/125826073-d65ed4d3-7b21-45fa-9fd0-c49ec572cdf3.png)

**Comment by harnishdesign** [comment]
We have fixed. Please refresh page & then check it again. The issue was caused by the long hypertext. Thanks.
